{
 "title": "Performance Dashboard Data",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   { "name": "ds", "label": "datasource", "query": "prometheus" },
   { "name": "cluster", "label": "Cluster", "query": { "query": "label_values(quobyte_cluster)" } },
   { "name": "percentile", "query": "1.0,0.99,0.95,0.1" }
  ]
 },
 "panels": [
  { "title": "General Cluster Resources", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "CPU Load",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 13, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "avg(quobyte_server_cpu_load{quobyte_cluster=\"$cluster\"} / quobyte_server_num_cores) by (hostname)",
     "legendFormat": "{{hostname}}"
    }
   ]
  },
  {
   "title": "CPU Load",
   "type": "text",
   "gridPos": { "h": 7, "w": 4, "x": 13, "y": 1 },
   "options": {
    "content": "CPU load as shown by top and other tools. It is the number of threads in runnable state. It should not considerably exceed 100%. \n\nIf the CPU load is very high it will cause performance problems. This may be due to slow CPUs or too small service heap space. Adjust MAX_MEM_*"
   }
  },
  { "title": "Metadata", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 } },
  {
   "title": "Page Fault Rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 13, "x": 0, "y": 9 },
   "targets": [
    {
     "expr": "irate(quobyte_service_major_page_fault_count{service_type=\"quobyte-metadata\", quobyte_cluster=\"$cluster\"}[5m])",
     "legendFormat": "{{hostname}}"
    }
   ]
  },
  {
   "title": "Page Fault Rate",
   "type": "text",
   "gridPos": { "h": 8, "w": 4, "x": 13, "y": 9 },
   "options": {
    "content": "Shows page faults per second. This means data had to be loaded from disk because it did not fit into RAM.\nFor metadata service this means usually that the footprint of database checkpoints exceeds the amount of memory available.\n\nCheck your memory setup or get more RAM."
   }
  },
  {
   "title": "Metadata Heap Memory Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 13, "x": 0, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "quobyte_jvm_memory_heap_used_bytes{service_type=\"quobyte-metadata\", quobyte_cluster=\"$cluster\"} / quobyte_jvm_memory_heap_max_bytes",
     "legendFormat": "{{value}} {{hostname}} "
    }
   ]
  },
  {
   "title": "Metadata Heap Memory Usage",
   "type": "text",
   "gridPos": { "h": 8, "w": 4, "x": 13, "y": 17 },
   "options": {
    "content": "If heap usage is at 100% for a longer period of time, increase heap space."
   }
  },
  {
   "title": "Checkpoint Lookup Latency",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 13, "x": 0, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "µs" } },
   "targets": [
    {
     "expr": "histogram_quantile($percentile, sum(irate(quobyte_db_blockreader_lookup_latency_micros_bucket{service_type=\"quobyte-metadata\", quobyte_cluster=\"$cluster\"}[5m])) by (le, hostname))",
     "legendFormat": "{{hostname}}"
    }
   ]
  },
  {
   "title": "Checkpoint Lookup Latency",
   "type": "text",
   "gridPos": { "h": 8, "w": 4, "x": 13, "y": 25 },
   "options": {
    "content": "Lookup latency for data in checkpoints. \n\nHigh latency either means that data had to be fetched from disk (see page fault rate) or CPU is busy."
   }
  },
  {
   "title": "Transaction Commit Latency",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 13, "x": 0, "y": 33 },
   "fieldConfig": { "defaults": { "unit": "µs" } },
   "targets": [
    {
     "expr": "histogram_quantile($percentile, sum(irate(quobyte_db_update_latency_micros_bucket{service_type=\"quobyte-metadata\", quobyte_cluster=\"$cluster\"}[5m])) by (le, device_id, hostname))",
     "legendFormat": "{{hostname}} {{device_id}}"
    }
   ]
  },
  {
   "title": "Transaction Commit Latency",
   "type": "text",
   "gridPos": { "h": 8, "w": 4, "x": 13, "y": 33 },
   "options": {
    "content": "Full stack latency including replication and persistence."
   }
  },
  {
   "title": "Replication Roundtrip Latency",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 13, "x": 0, "y": 41 },
   "fieldConfig": { "defaults": { "unit": "µs" } },
   "targets": [
    {
     "expr": "histogram_quantile($percentile, sum(irate(quobyte_db_replication_backup_roundtrip_latency_micros_bucket{service_type=\"quobyte-metadata\", quobyte_cluster=\"$cluster\"}[5m])) by (le, device_id, hostname))",
     "legendFormat": "{{hostname}} => {{device_id}}"
    }
   ]
  },
  {
   "title": "Replication Roundtrip Latency",
   "type": "text",
   "gridPos": { "h": 8, "w": 4, "x": 13, "y": 41 },
   "options": {
    "content": "Replication latency measured by the primary, ie. network roundtrip and backup persistence."
   }
  },
  {
   "title": "Backup Processing Latency",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 13, "x": 0, "y": 49 },
   "fieldConfig": { "defaults": { "unit": "µs" } },
   "targets": [
    {
     "expr": "histogram_quantile($percentile, sum(irate(quobyte_db_replication_backup_processing_latency_micros_bucket{service_type=\"quobyte-metadata\", quobyte_cluster=\"$cluster\"}[5m])) by (le, device_id, hostname))",
     "legendFormat": "{{hostname}} {{device_id}}"
    }
   ]
  },
  {
   "title": "Backup Processing Latency",
   "type": "text",
   "gridPos": { "h": 8, "w": 4, "x": 13, "y": 49 },
   "options": {
    "content": "Processing and persistence latency measured on backup replicas.\n\nA delta between \"Replication roundtrip latency\" and \"Backup processing latency\" indicates network problems."
   }
  },
  {
   "title": "RPC Rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 13, "x": 0, "y": 57 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "irate(quobyte_rpc_server_rpcs_received{service_type=\"quobyte-metadata\", quobyte_cluster=\"$cluster\"}[5m])",
     "legendFormat": "{{hostname}}"
    }
   ]
  },
  {
   "title": "RPC Rate",
   "type": "text",
   "gridPos": { "h": 8, "w": 4, "x": 13, "y": 57 },
   "options": {
    "content": "Overall rate of metadata operations."
   }
  },
  {
   "title": "Backpressure by Admission Control",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 13, "x": 0, "y": 65 },
   "targets": [
    {
     "expr": "irate(quobyte_rpc_server_total_global_blocked_connections{service_type=\"quobyte-metadata\", quobyte_cluster=\"$cluster\"}[5m])",
     "legendFormat": "{{hostname}}"
    }
   ]
  },
  {
   "title": "Backpressure by Admission Control",
   "type": "text",
   "gridPos": { "h": 8, "w": 4, "x": 13, "y": 65 },
   "options": {
    "content": "Metadata service throttles client RPCs because it can't keep up with processing. \n\nShould always be zero."
   }
  },
  {
   "title": "Backpressure due to Checkpointing",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 13, "x": 0, "y": 73 },
   "targets": [
    {
     "expr": "sum(irate(quobyte_db_checkpointing_backpressure_queue_full_errors{service_type=\"quobyte-metadata\", quobyte_cluster=\"$cluster\"}[5m])) by (hostname)",
     "legendFormat": "{{hostname}}"
    }
   ]
  },
  {
   "title": "Backpressure due to Checkpointing",
   "type": "text",
   "gridPos": { "h": 8, "w": 4, "x": 13, "y": 73 },
   "options": {
    "content": "Metadata service failing client RPCs because it can't keep up with checkpointing. \n\nShould always be zero."
   }
  },
  { "title": "Data Service", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 81 } },
  {
   "title": "Data Heap Memory Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 13, "x": 0, "y": 82 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "quobyte_jvm_memory_heap_used_bytes{service_type=\"quobyte-data\", quobyte_cluster=\"$cluster\"} / quobyte_jvm_memory_heap_max_bytes",
     "legendFormat": "{{value}} {{hostname}} "
    }
   ]
  },
  {
   "title": "Data Heap Memory Usage",
   "type": "text",
   "gridPos": { "h": 8, "w": 4, "x": 13, "y": 82 },
   "options": {
    "content": "If heap usage is at 100% for a longer period of time, increase heap space."
   }
  },
  {
   "title": "Backpressure by Admission Control",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 13, "x": 0, "y": 90 },
   "targets": [
    {
     "expr": "irate(quobyte_rpc_server_blocked_connection_duration_normal_high_micros_count{service_type=\"quobyte-data\", quobyte_cluster=\"$cluster\"}[5m])",
     "legendFormat": "{{hostname}}"
    }
   ]
  },
  {
   "title": "Backpressure by Admission Control",
   "type": "text",
   "gridPos": { "h": 8, "w": 4, "x": 13, "y": 90 },
   "options": {
    "content": "Incoming request cannot be handled because of backpressure. This can be due to busy devices or buffer memory limits.\n\nIf devices are not saturated, increase MAX_BUFFER_DATA."
   }
  },
  {
   "title": "Number of open files",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 13, "x": 0, "y": 98 },
   "targets": [
    {
     "expr": "sum(quobyte_osd_preproc_open_files{service_type=\"quobyte-data\", quobyte_cluster=\"$cluster\"}) by (hostname)",
     "legendFormat": "{{hostname}}"
    }
   ]
  },
  {
   "title": "Number of open files",
   "type": "text",
   "gridPos": { "h": 8, "w": 4, "x": 13, "y": 98 },
   "options": {
    "content": "Displays the number of open files per host.\n\n"
   }
  },
  {
   "title": "Saturated devices",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 13, "x": 0, "y": 106 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "topk(10, rate(quobyte_osd_storage_busy_time_millis{service_type=\"quobyte-data\", quobyte_cluster=\"$cluster\"}[10m]) / 1000) > 0.90",
     "legendFormat": "{{device_id}} ({{device_hardware_type}})"
    }
   ]
  },
  {
   "title": "Saturated devices",
   "type": "text",
   "gridPos": { "h": 8, "w": 4, "x": 13, "y": 106 },
   "options": {
    "content": "Displays devices that show high utilization over time.\nDevices shown here can be considered a bottleneck. \n\nUse more devices e.g by increasing stripe width or use faster devices."
   }
  },
  {
   "title": "Replication Roundtrip Latency",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 13, "x": 0, "y": 114 },
   "fieldConfig": { "defaults": { "unit": "µs" } },
   "targets": [
    {
     "expr": "histogram_quantile($percentile, sum(irate(quobyte_osd_replication_roundtrip_latency_micros_bucket{service_type=\"quobyte-data\", quobyte_cluster=\"$cluster\"}[5m])) by (le, hostname))",
     "legendFormat": "{{hostname}}"
    }
   ]
  },
  {
   "title": "Replication Roundtrip Latency",
   "type": "text",
   "gridPos": { "h": 8, "w": 4, "x": 13, "y": 114 },
   "options": {
    "content": "Replication latency measured by the primary, ie. network roundtrip and backup persistence."
   }
  },
  {
   "title": "Read Bands: Page Cache, Device Reads Relaxed, Device Reads Busy",
   "type": "timeseries",
   "description": "Interprets device latency reads from data service.\n\nYou should be able to identify saturated disks.",
   "gridPos": { "h": 8, "w": 13, "x": 0, "y": 122 },
   "targets": [
    {
     "expr": "sum(irate(quobyte_osd_storage_device_read_latency_micros_bucket{le=\"100000\"}[5m])) - sum(irate(quobyte_osd_storage_device_read_latency_micros_bucket{le=\"1000\"}[5m]))",
     "legendFormat": "device reads normal"
    },
    {
     "expr": "sum(irate(quobyte_osd_storage_device_read_latency_micros_bucket{le=\"100000\"}[5m])) - sum(irate(quobyte_osd_storage_device_read_latency_micros_bucket{le=\"10\"}[5m]))",
     "legendFormat": "cache reads"
    },
    {
     "expr": "sum(irate(quobyte_osd_storage_device_read_latency_micros_bucket{le=\"10000000\"}[5m])) - sum(irate(quobyte_osd_storage_device_read_latency_micros_bucket{le=\"100000\"}[5m]))",
     "legendFormat": "device reads busy"
    }
   ]
  },
  {
   "title": "Write Bands: Device Writes Relaxed, Device Writes Busy",
   "type": "timeseries",
   "description": "Interprets devicewrite latency from data service.\n\nYou should be able to identify saturated disks.",
   "gridPos": { "h": 8, "w": 13, "x": 0, "y": 130 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(irate(quobyte_osd_storage_device_write_latency_micros_bucket{le=\"1000\"}[5m])) - sum(irate(quobyte_osd_storage_device_write_latency_micros_bucket{le=\"10\"}[5m]))",
     "legendFormat": "device writes unexpected fast"
    },
    {
     "expr": "sum(irate(quobyte_osd_storage_device_write_latency_micros_bucket{le=\"100000\"}[5m])) - sum(irate(quobyte_osd_storage_device_write_latency_micros_bucket{le=\"1000\"}[5m]))",
     "legendFormat": "device writes normal"
    },
    {
     "expr": "sum(irate(quobyte_osd_storage_device_write_latency_micros_bucket{le=\"10000000\"}[5m])) - sum(irate(quobyte_osd_storage_device_write_latency_micros_bucket{le=\"100000\"}[5m]))",
     "legendFormat": "device writes busy"
    }
   ]
  }
 ]
}